// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: peer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash     string                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

func (x *GetChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type ChunkDataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsEof         bool                   `protobuf:"varint,4,opt,name=is_eof,json=isEof,proto3" json:"is_eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDataChunk) Reset() {
	*x = ChunkDataChunk{}
	mi := &file_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDataChunk) ProtoMessage() {}

func (x *ChunkDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDataChunk.ProtoReflect.Descriptor instead.
func (*ChunkDataChunk) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkDataChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChunkDataChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkDataChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ChunkDataChunk) GetIsEof() bool {
	if x != nil {
		return x.IsEof
	}
	return false
}

type SyncArtifactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson    string                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	OriginType      string                 `protobuf:"bytes,3,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`
	OriginUri       string                 `protobuf:"bytes,4,opt,name=origin_uri,json=originUri,proto3" json:"origin_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncArtifactRequest) Reset() {
	*x = SyncArtifactRequest{}
	mi := &file_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncArtifactRequest) ProtoMessage() {}

func (x *SyncArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncArtifactRequest.ProtoReflect.Descriptor instead.
func (*SyncArtifactRequest) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{2}
}

func (x *SyncArtifactRequest) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *SyncArtifactRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *SyncArtifactRequest) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *SyncArtifactRequest) GetOriginUri() string {
	if x != nil {
		return x.OriginUri
	}
	return ""
}

type SyncArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncArtifactResponse) Reset() {
	*x = SyncArtifactResponse{}
	mi := &file_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncArtifactResponse) ProtoMessage() {}

func (x *SyncArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncArtifactResponse.ProtoReflect.Descriptor instead.
func (*SyncArtifactResponse) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{3}
}

func (x *SyncArtifactResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SyncArtifactResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SyncArtifactResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SyncJobStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ArtifactId       string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalChunks      int64                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	DownloadedChunks int64                  `protobuf:"varint,5,opt,name=downloaded_chunks,json=downloadedChunks,proto3" json:"downloaded_chunks,omitempty"`
	PeerChunks       int64                  `protobuf:"varint,6,opt,name=peer_chunks,json=peerChunks,proto3" json:"peer_chunks,omitempty"`
	OriginChunks     int64                  `protobuf:"varint,7,opt,name=origin_chunks,json=originChunks,proto3" json:"origin_chunks,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SkippedChunks    int64                  `protobuf:"varint,9,opt,name=skipped_chunks,json=skippedChunks,proto3" json:"skipped_chunks,omitempty"`
	PeerBytes        int64                  `protobuf:"varint,10,opt,name=peer_bytes,json=peerBytes,proto3" json:"peer_bytes,omitempty"`
	OriginBytes      int64                  `protobuf:"varint,11,opt,name=origin_bytes,json=originBytes,proto3" json:"origin_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncJobStatus) Reset() {
	*x = SyncJobStatus{}
	mi := &file_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobStatus) ProtoMessage() {}

func (x *SyncJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobStatus.ProtoReflect.Descriptor instead.
func (*SyncJobStatus) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{5}
}

func (x *SyncJobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SyncJobStatus) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *SyncJobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncJobStatus) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *SyncJobStatus) GetDownloadedChunks() int64 {
	if x != nil {
		return x.DownloadedChunks
	}
	return 0
}

func (x *SyncJobStatus) GetPeerChunks() int64 {
	if x != nil {
		return x.PeerChunks
	}
	return 0
}

func (x *SyncJobStatus) GetOriginChunks() int64 {
	if x != nil {
		return x.OriginChunks
	}
	return 0
}

func (x *SyncJobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SyncJobStatus) GetSkippedChunks() int64 {
	if x != nil {
		return x.SkippedChunks
	}
	return 0
}

func (x *SyncJobStatus) GetPeerBytes() int64 {
	if x != nil {
		return x.PeerBytes
	}
	return 0
}

func (x *SyncJobStatus) GetOriginBytes() int64 {
	if x != nil {
		return x.OriginBytes
	}
	return 0
}

type GetNodeStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CachedChunks     int64                  `protobuf:"varint,2,opt,name=cached_chunks,json=cachedChunks,proto3" json:"cached_chunks,omitempty"`
	TotalBytesCached int64                  `protobuf:"varint,3,opt,name=total_bytes_cached,json=totalBytesCached,proto3" json:"total_bytes_cached,omitempty"`
	ActiveJobs       []*SyncJobStatus       `protobuf:"bytes,4,rep,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodeStatusResponse) Reset() {
	*x = GetNodeStatusResponse{}
	mi := &file_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusResponse) ProtoMessage() {}

func (x *GetNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeStatusResponse) GetCachedChunks() int64 {
	if x != nil {
		return x.CachedChunks
	}
	return 0
}

func (x *GetNodeStatusResponse) GetTotalBytesCached() int64 {
	if x != nil {
		return x.TotalBytesCached
	}
	return 0
}

func (x *GetNodeStatusResponse) GetActiveJobs() []*SyncJobStatus {
	if x != nil {
		return x.ActiveJobs
	}
	return nil
}

var File_peer_proto protoreflect.FileDescriptor

const file_peer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"peer.proto\x12\x06api.v1\"0\n" +
	"\x0fGetChunkRequest\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\"x\n" +
	"\x0eChunkDataChunk\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x15\n" +
	"\x06is_eof\x18\x04 \x01(\bR\x05isEof\"\xa5\x01\n" +
	"\x13SyncArtifactRequest\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\tR\fmanifestJson\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x12\x1f\n" +
	"\vorigin_type\x18\x03 \x01(\tR\n" +
	"originType\x12\x1d\n" +
	"\n" +
	"origin_uri\x18\x04 \x01(\tR\toriginUri\"c\n" +
	"\x14SyncArtifactResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"-\n" +
	"\x14GetNodeStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x83\x03\n" +
	"\rSyncJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x03R\vtotalChunks\x12+\n" +
	"\x11downloaded_chunks\x18\x05 \x01(\x03R\x10downloadedChunks\x12\x1f\n" +
	"\vpeer_chunks\x18\x06 \x01(\x03R\n" +
	"peerChunks\x12#\n" +
	"\rorigin_chunks\x18\a \x01(\x03R\foriginChunks\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eskipped_chunks\x18\t \x01(\x03R\rskippedChunks\x12\x1d\n" +
	"\n" +
	"peer_bytes\x18\n" +
	" \x01(\x03R\tpeerBytes\x12!\n" +
	"\forigin_bytes\x18\v \x01(\x03R\voriginBytes\"\xbb\x01\n" +
	"\x15GetNodeStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rcached_chunks\x18\x02 \x01(\x03R\fcachedChunks\x12,\n" +
	"\x12total_bytes_cached\x18\x03 \x01(\x03R\x10totalBytesCached\x126\n" +
	"\vactive_jobs\x18\x04 \x03(\v2\x15.api.v1.SyncJobStatusR\n" +
	"activeJobs2\xe5\x01\n" +
	"\vPeerService\x12=\n" +
	"\bGetChunk\x12\x17.api.v1.GetChunkRequest\x1a\x16.api.v1.ChunkDataChunk0\x01\x12I\n" +
	"\fSyncArtifact\x12\x1b.api.v1.SyncArtifactRequest\x1a\x1c.api.v1.SyncArtifactResponse\x12L\n" +
	"\rGetNodeStatus\x12\x1c.api.v1.GetNodeStatusRequest\x1a\x1d.api.v1.GetNodeStatusResponseB\x1bZ\x19spider/api/v1/proto;protob\x06proto3"

var (
	file_peer_proto_rawDescOnce sync.Once
	file_peer_proto_rawDescData []byte
)

func file_peer_proto_rawDescGZIP() []byte {
	file_peer_proto_rawDescOnce.Do(func() {
		file_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)))
	})
	return file_peer_proto_rawDescData
}

var file_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_peer_proto_goTypes = []any{
	(*GetChunkRequest)(nil),       // 0: api.v1.GetChunkRequest
	(*ChunkDataChunk)(nil),        // 1: api.v1.ChunkDataChunk
	(*SyncArtifactRequest)(nil),   // 2: api.v1.SyncArtifactRequest
	(*SyncArtifactResponse)(nil),  // 3: api.v1.SyncArtifactResponse
	(*GetNodeStatusRequest)(nil),  // 4: api.v1.GetNodeStatusRequest
	(*SyncJobStatus)(nil),         // 5: api.v1.SyncJobStatus
	(*GetNodeStatusResponse)(nil), // 6: api.v1.GetNodeStatusResponse
}
var file_peer_proto_depIdxs = []int32{
	5, // 0: api.v1.GetNodeStatusResponse.active_jobs:type_name -> api.v1.SyncJobStatus
	0, // 1: api.v1.PeerService.GetChunk:input_type -> api.v1.GetChunkRequest
	2, // 2: api.v1.PeerService.SyncArtifact:input_type -> api.v1.SyncArtifactRequest
	4, // 3: api.v1.PeerService.GetNodeStatus:input_type -> api.v1.GetNodeStatusRequest
	1, // 4: api.v1.PeerService.GetChunk:output_type -> api.v1.ChunkDataChunk
	3, // 5: api.v1.PeerService.SyncArtifact:output_type -> api.v1.SyncArtifactResponse
	6, // 6: api.v1.PeerService.GetNodeStatus:output_type -> api.v1.GetNodeStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peer_proto_init() }
func file_peer_proto_init() {
	if File_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_proto_goTypes,
		DependencyIndexes: file_peer_proto_depIdxs,
		MessageInfos:      file_peer_proto_msgTypes,
	}.Build()
	File_peer_proto = out.File
	file_peer_proto_goTypes = nil
	file_peer_proto_depIdxs = nil
}
