// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: tracker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Rack          string                 `protobuf:"bytes,5,opt,name=rack,proto3" json:"rack,omitempty"`
	Host          string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,7,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerInfo) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PeerInfo) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *PeerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PeerInfo) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPeerRequest) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type DeregisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPeerRequest) Reset() {
	*x = DeregisterPeerRequest{}
	mi := &file_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPeerRequest) ProtoMessage() {}

func (x *DeregisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPeerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterPeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeregisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPeerResponse) Reset() {
	*x = DeregisterPeerResponse{}
	mi := &file_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPeerResponse) ProtoMessage() {}

func (x *DeregisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPeerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChunksRequest) Reset() {
	*x = ReportChunksRequest{}
	mi := &file_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunksRequest) ProtoMessage() {}

func (x *ReportChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunksRequest.ProtoReflect.Descriptor instead.
func (*ReportChunksRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *ReportChunksRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportChunksRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type ReportChunksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunksRecorded int64                  `protobuf:"varint,1,opt,name=chunks_recorded,json=chunksRecorded,proto3" json:"chunks_recorded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportChunksResponse) Reset() {
	*x = ReportChunksResponse{}
	mi := &file_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunksResponse) ProtoMessage() {}

func (x *ReportChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunksResponse.ProtoReflect.Descriptor instead.
func (*ReportChunksResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *ReportChunksResponse) GetChunksRecorded() int64 {
	if x != nil {
		return x.ChunksRecorded
	}
	return 0
}

type LocateChunksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	ChunkHashes     []string               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocateChunksRequest) Reset() {
	*x = LocateChunksRequest{}
	mi := &file_tracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateChunksRequest) ProtoMessage() {}

func (x *LocateChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateChunksRequest.ProtoReflect.Descriptor instead.
func (*LocateChunksRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{9}
}

func (x *LocateChunksRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

func (x *LocateChunksRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type ChunkLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash     string                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	Peers         []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocation) Reset() {
	*x = ChunkLocation{}
	mi := &file_tracker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocation) ProtoMessage() {}

func (x *ChunkLocation) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocation.ProtoReflect.Descriptor instead.
func (*ChunkLocation) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{10}
}

func (x *ChunkLocation) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *ChunkLocation) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type LocateChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*ChunkLocation       `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateChunksResponse) Reset() {
	*x = LocateChunksResponse{}
	mi := &file_tracker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateChunksResponse) ProtoMessage() {}

func (x *LocateChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateChunksResponse.ProtoReflect.Descriptor instead.
func (*LocateChunksResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{11}
}

func (x *LocateChunksResponse) GetLocations() []*ChunkLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_tracker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{12}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_tracker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{13}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PutArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ManifestJson  []byte                 `protobuf:"bytes,4,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArtifactRequest) Reset() {
	*x = PutArtifactRequest{}
	mi := &file_tracker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArtifactRequest) ProtoMessage() {}

func (x *PutArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArtifactRequest.ProtoReflect.Descriptor instead.
func (*PutArtifactRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{14}
}

func (x *PutArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *PutArtifactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutArtifactRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PutArtifactRequest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type PutArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArtifactResponse) Reset() {
	*x = PutArtifactResponse{}
	mi := &file_tracker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArtifactResponse) ProtoMessage() {}

func (x *PutArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArtifactResponse.ProtoReflect.Descriptor instead.
func (*PutArtifactResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{15}
}

func (x *PutArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArtifactRequest) Reset() {
	*x = ReportArtifactRequest{}
	mi := &file_tracker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArtifactRequest) ProtoMessage() {}

func (x *ReportArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArtifactRequest.ProtoReflect.Descriptor instead.
func (*ReportArtifactRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{16}
}

func (x *ReportArtifactRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ReportArtifactRequest) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type ReportArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArtifactResponse) Reset() {
	*x = ReportArtifactResponse{}
	mi := &file_tracker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArtifactResponse) ProtoMessage() {}

func (x *ReportArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArtifactResponse.ProtoReflect.Descriptor instead.
func (*ReportArtifactResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{17}
}

func (x *ReportArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LocateArtifactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	ArtifactId      string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocateArtifactRequest) Reset() {
	*x = LocateArtifactRequest{}
	mi := &file_tracker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateArtifactRequest) ProtoMessage() {}

func (x *LocateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateArtifactRequest.ProtoReflect.Descriptor instead.
func (*LocateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{18}
}

func (x *LocateArtifactRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

func (x *LocateArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type LocateArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	SeedPeers     []*PeerInfo            `protobuf:"bytes,2,rep,name=seed_peers,json=seedPeers,proto3" json:"seed_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateArtifactResponse) Reset() {
	*x = LocateArtifactResponse{}
	mi := &file_tracker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateArtifactResponse) ProtoMessage() {}

func (x *LocateArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateArtifactResponse.ProtoReflect.Descriptor instead.
func (*LocateArtifactResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{19}
}

func (x *LocateArtifactResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *LocateArtifactResponse) GetSeedPeers() []*PeerInfo {
	if x != nil {
		return x.SeedPeers
	}
	return nil
}

type GetArtifactStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactStatusRequest) Reset() {
	*x = GetArtifactStatusRequest{}
	mi := &file_tracker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactStatusRequest) ProtoMessage() {}

func (x *GetArtifactStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactStatusRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactStatusRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{20}
}

func (x *GetArtifactStatusRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId      string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	TotalChunks     int64                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	CompletedChunks int64                  `protobuf:"varint,3,opt,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	ReadyNodes      []string               `protobuf:"bytes,4,rep,name=ready_nodes,json=readyNodes,proto3" json:"ready_nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetArtifactStatusResponse) Reset() {
	*x = GetArtifactStatusResponse{}
	mi := &file_tracker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactStatusResponse) ProtoMessage() {}

func (x *GetArtifactStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactStatusResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactStatusResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{21}
}

func (x *GetArtifactStatusResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *GetArtifactStatusResponse) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *GetArtifactStatusResponse) GetCompletedChunks() int64 {
	if x != nil {
		return x.CompletedChunks
	}
	return 0
}

func (x *GetArtifactStatusResponse) GetReadyNodes() []string {
	if x != nil {
		return x.ReadyNodes
	}
	return nil
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\x06api.v1\"\xb7\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x12\n" +
	"\x04rack\x18\x05 \x01(\tR\x04rack\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12$\n" +
	"\x0elast_seen_unix\x18\a \x01(\x03R\flastSeenUnix\";\n" +
	"\x13RegisterPeerRequest\x12$\n" +
	"\x04peer\x18\x01 \x01(\v2\x10.api.v1.PeerInfoR\x04peer\"J\n" +
	"\x14RegisterPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"0\n" +
	"\x15DeregisterPeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"2\n" +
	"\x16DeregisterPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x13ReportChunksRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\tR\vchunkHashes\"?\n" +
	"\x14ReportChunksResponse\x12'\n" +
	"\x0fchunks_recorded\x18\x01 \x01(\x03R\x0echunksRecorded\"d\n" +
	"\x13LocateChunksRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\tR\vchunkHashes\"V\n" +
	"\rChunkLocation\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\x12&\n" +
	"\x05peers\x18\x02 \x03(\v2\x10.api.v1.PeerInfoR\x05peers\"K\n" +
	"\x14LocateChunksResponse\x123\n" +
	"\tlocations\x18\x01 \x03(\v2\x15.api.v1.ChunkLocationR\tlocations\"\x12\n" +
	"\x10ListPeersRequest\";\n" +
	"\x11ListPeersResponse\x12&\n" +
	"\x05peers\x18\x01 \x03(\v2\x10.api.v1.PeerInfoR\x05peers\"\x88\x01\n" +
	"\x12PutArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rmanifest_json\x18\x04 \x01(\fR\fmanifestJson\"/\n" +
	"\x13PutArtifactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x15ReportArtifactRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\"2\n" +
	"\x16ReportArtifactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x15LocateArtifactRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"j\n" +
	"\x16LocateArtifactResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12/\n" +
	"\n" +
	"seed_peers\x18\x02 \x03(\v2\x10.api.v1.PeerInfoR\tseedPeers\";\n" +
	"\x18GetArtifactStatusRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"\xab\x01\n" +
	"\x19GetArtifactStatusResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x03R\vtotalChunks\x12)\n" +
	"\x10completed_chunks\x18\x03 \x01(\x03R\x0fcompletedChunks\x12\x1f\n" +
	"\vready_nodes\x18\x04 \x03(\tR\n" +
	"readyNodes2\x8a\x06\n" +
	"\x0eTrackerService\x12I\n" +
	"\fRegisterPeer\x12\x1b.api.v1.RegisterPeerRequest\x1a\x1c.api.v1.RegisterPeerResponse\x12@\n" +
	"\tHeartbeat\x12\x18.api.v1.HeartbeatRequest\x1a\x19.api.v1.HeartbeatResponse\x12O\n" +
	"\x0eDeregisterPeer\x12\x1d.api.v1.DeregisterPeerRequest\x1a\x1e.api.v1.DeregisterPeerResponse\x12I\n" +
	"\fReportChunks\x12\x1b.api.v1.ReportChunksRequest\x1a\x1c.api.v1.ReportChunksResponse\x12I\n" +
	"\fLocateChunks\x12\x1b.api.v1.LocateChunksRequest\x1a\x1c.api.v1.LocateChunksResponse\x12@\n" +
	"\tListPeers\x12\x18.api.v1.ListPeersRequest\x1a\x19.api.v1.ListPeersResponse\x12F\n" +
	"\vPutArtifact\x12\x1a.api.v1.PutArtifactRequest\x1a\x1b.api.v1.PutArtifactResponse\x12O\n" +
	"\x0eReportArtifact\x12\x1d.api.v1.ReportArtifactRequest\x1a\x1e.api.v1.ReportArtifactResponse\x12O\n" +
	"\x0eLocateArtifact\x12\x1d.api.v1.LocateArtifactRequest\x1a\x1e.api.v1.LocateArtifactResponse\x12X\n" +
	"\x11GetArtifactStatus\x12 .api.v1.GetArtifactStatusRequest\x1a!.api.v1.GetArtifactStatusResponseB\x1bZ\x19spider/api/v1/proto;protob\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_tracker_proto_goTypes = []any{
	(*PeerInfo)(nil),                  // 0: api.v1.PeerInfo
	(*RegisterPeerRequest)(nil),       // 1: api.v1.RegisterPeerRequest
	(*RegisterPeerResponse)(nil),      // 2: api.v1.RegisterPeerResponse
	(*HeartbeatRequest)(nil),          // 3: api.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 4: api.v1.HeartbeatResponse
	(*DeregisterPeerRequest)(nil),     // 5: api.v1.DeregisterPeerRequest
	(*DeregisterPeerResponse)(nil),    // 6: api.v1.DeregisterPeerResponse
	(*ReportChunksRequest)(nil),       // 7: api.v1.ReportChunksRequest
	(*ReportChunksResponse)(nil),      // 8: api.v1.ReportChunksResponse
	(*LocateChunksRequest)(nil),       // 9: api.v1.LocateChunksRequest
	(*ChunkLocation)(nil),             // 10: api.v1.ChunkLocation
	(*LocateChunksResponse)(nil),      // 11: api.v1.LocateChunksResponse
	(*ListPeersRequest)(nil),          // 12: api.v1.ListPeersRequest
	(*ListPeersResponse)(nil),         // 13: api.v1.ListPeersResponse
	(*PutArtifactRequest)(nil),        // 14: api.v1.PutArtifactRequest
	(*PutArtifactResponse)(nil),       // 15: api.v1.PutArtifactResponse
	(*ReportArtifactRequest)(nil),     // 16: api.v1.ReportArtifactRequest
	(*ReportArtifactResponse)(nil),    // 17: api.v1.ReportArtifactResponse
	(*LocateArtifactRequest)(nil),     // 18: api.v1.LocateArtifactRequest
	(*LocateArtifactResponse)(nil),    // 19: api.v1.LocateArtifactResponse
	(*GetArtifactStatusRequest)(nil),  // 20: api.v1.GetArtifactStatusRequest
	(*GetArtifactStatusResponse)(nil), // 21: api.v1.GetArtifactStatusResponse
}
var file_tracker_proto_depIdxs = []int32{
	0,  // 0: api.v1.RegisterPeerRequest.peer:type_name -> api.v1.PeerInfo
	0,  // 1: api.v1.ChunkLocation.peers:type_name -> api.v1.PeerInfo
	10, // 2: api.v1.LocateChunksResponse.locations:type_name -> api.v1.ChunkLocation
	0,  // 3: api.v1.ListPeersResponse.peers:type_name -> api.v1.PeerInfo
	0,  // 4: api.v1.LocateArtifactResponse.seed_peers:type_name -> api.v1.PeerInfo
	1,  // 5: api.v1.TrackerService.RegisterPeer:input_type -> api.v1.RegisterPeerRequest
	3,  // 6: api.v1.TrackerService.Heartbeat:input_type -> api.v1.HeartbeatRequest
	5,  // 7: api.v1.TrackerService.DeregisterPeer:input_type -> api.v1.DeregisterPeerRequest
	7,  // 8: api.v1.TrackerService.ReportChunks:input_type -> api.v1.ReportChunksRequest
	9,  // 9: api.v1.TrackerService.LocateChunks:input_type -> api.v1.LocateChunksRequest
	12, // 10: api.v1.TrackerService.ListPeers:input_type -> api.v1.ListPeersRequest
	14, // 11: api.v1.TrackerService.PutArtifact:input_type -> api.v1.PutArtifactRequest
	16, // 12: api.v1.TrackerService.ReportArtifact:input_type -> api.v1.ReportArtifactRequest
	18, // 13: api.v1.TrackerService.LocateArtifact:input_type -> api.v1.LocateArtifactRequest
	20, // 14: api.v1.TrackerService.GetArtifactStatus:input_type -> api.v1.GetArtifactStatusRequest
	2,  // 15: api.v1.TrackerService.RegisterPeer:output_type -> api.v1.RegisterPeerResponse
	4,  // 16: api.v1.TrackerService.Heartbeat:output_type -> api.v1.HeartbeatResponse
	6,  // 17: api.v1.TrackerService.DeregisterPeer:output_type -> api.v1.DeregisterPeerResponse
	8,  // 18: api.v1.TrackerService.ReportChunks:output_type -> api.v1.ReportChunksResponse
	11, // 19: api.v1.TrackerService.LocateChunks:output_type -> api.v1.LocateChunksResponse
	13, // 20: api.v1.TrackerService.ListPeers:output_type -> api.v1.ListPeersResponse
	15, // 21: api.v1.TrackerService.PutArtifact:output_type -> api.v1.PutArtifactResponse
	17, // 22: api.v1.TrackerService.ReportArtifact:output_type -> api.v1.ReportArtifactResponse
	19, // 23: api.v1.TrackerService.LocateArtifact:output_type -> api.v1.LocateArtifactResponse
	21, // 24: api.v1.TrackerService.GetArtifactStatus:output_type -> api.v1.GetArtifactStatusResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
